config/routes.rb
Tarea2::Application.routes.draw do
  resources :my_scaffolds

end

app/models/my_scaffold.rb
class MyScaffold < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_scaffolds_controller.rb
class MyScaffoldsController < ApplicationController
  before_action :set_my_scaffold, only: [:show, :edit, :update, :destroy]

  # GET /my_scaffolds
  # GET /my_scaffolds.json
  def index
    @my_scaffolds = MyScaffold.all
  end

  # GET /my_scaffolds/1
  # GET /my_scaffolds/1.json
  def show
  end

  # GET /my_scaffolds/new
  def new
    @my_scaffold = MyScaffold.new
  end

  # GET /my_scaffolds/1/edit
  def edit
  end

  # POST /my_scaffolds
  # POST /my_scaffolds.json
  def create
    @my_scaffold = MyScaffold.new(my_scaffold_params)

    respond_to do |format|
      if @my_scaffold.save
        format.html { redirect_to @my_scaffold, notice: 'My scaffold was successfully created.' }
        format.json { render action: 'show', status: :created, location: @my_scaffold }
      else
        format.html { render action: 'new' }
        format.json { render json: @my_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_scaffolds/1
  # PATCH/PUT /my_scaffolds/1.json
  def update
    respond_to do |format|
      if @my_scaffold.update(my_scaffold_params)
        format.html { redirect_to @my_scaffold, notice: 'My scaffold was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @my_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_scaffolds/1
  # DELETE /my_scaffolds/1.json
  def destroy
    @my_scaffold.destroy
    respond_to do |format|
      format.html { redirect_to my_scaffolds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_scaffold
      @my_scaffold = MyScaffold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_scaffold_params
      params.require(:my_scaffold).permit(:my_string, :my_integer, :my_datetime, :my_boolean)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_scaffolds_helper.rb
module MyScaffoldsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarea2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_scaffolds/_form.html.erb
<%= form_for(@my_scaffold) do |f| %>
  <% if @my_scaffold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_scaffold.errors.count, "error") %> prohibited this my_scaffold from being saved:</h2>

      <ul>
      <% @my_scaffold.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_string %><br>
    <%= f.text_field :my_string %>
  </div>
  <div class="field">
    <%= f.label :my_integer %><br>
    <%= f.number_field :my_integer %>
  </div>
  <div class="field">
    <%= f.label :my_datetime %><br>
    <%= f.datetime_select :my_datetime %>
  </div>
  <div class="field">
    <%= f.label :my_boolean %><br>
    <%= f.check_box :my_boolean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_scaffolds/edit.html.erb
<h1>Editing my_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_scaffold %> |
<%= link_to 'Back', my_scaffolds_path %>

app/views/my_scaffolds/index.html.erb
<h1>Listing my_scaffolds</h1>

<table>
  <thead>
    <tr>
      <th>My string</th>
      <th>My integer</th>
      <th>My datetime</th>
      <th>My boolean</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @my_scaffolds.each do |my_scaffold| %>
      <tr>
        <td><%= my_scaffold.my_string %></td>
        <td><%= my_scaffold.my_integer %></td>
        <td><%= my_scaffold.my_datetime %></td>
        <td><%= my_scaffold.my_boolean %></td>
        <td><%= link_to 'Show', my_scaffold %></td>
        <td><%= link_to 'Edit', edit_my_scaffold_path(my_scaffold) %></td>
        <td><%= link_to 'Destroy', my_scaffold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My scaffold', new_my_scaffold_path %>

app/views/my_scaffolds/new.html.erb
<h1>New my_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Back', my_scaffolds_path %>

app/views/my_scaffolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My string:</strong>
  <%= @my_scaffold.my_string %>
</p>

<p>
  <strong>My integer:</strong>
  <%= @my_scaffold.my_integer %>
</p>

<p>
  <strong>My datetime:</strong>
  <%= @my_scaffold.my_datetime %>
</p>

<p>
  <strong>My boolean:</strong>
  <%= @my_scaffold.my_boolean %>
</p>

<%= link_to 'Edit', edit_my_scaffold_path(@my_scaffold) %> |
<%= link_to 'Back', my_scaffolds_path %>